In [14]:
## IMPORT NECESSARY LIBRARIES
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical



In [15]:
## LOADING THE DATASET
iris = load_iris()


In [16]:
## SEPARATING THE DATASET INTO FEATURES AND TARGET VALUES
X = iris.data
y = iris.target

print(X.shape)

print(y.shape)

(150, 4)
(150,)


In [17]:
##  PREPROCESSINF THE DATA BY SCALING THE FEATURES

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [18]:
## ONE HOT ENCODING THE TARGET LABELS
y_encoded = to_categorical(y, num_classes = 3)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
## SPLITTING THE DATASET INTO TRAINING AND TESTING SET
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120, 3)
(30, 4)
(30, 3)


In [20]:
## BUILDING THE ANN MODEL
model = Sequential()
model.add(Dense(32, input_dim=4, activation='relu'))
model.add(Dense(16, activation='elu'))
model.add(Dense(8, activation= 'elu'))
model.add(Dense(3, activation= 'softmax'))
print(model.summary())



Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 32)                160       
                                                                 
 dense_5 (Dense)             (None, 16)                528       
                                                                 
 dense_6 (Dense)             (None, 8)                 136       
                                                                 
 dense_7 (Dense)             (None, 3)                 27        
                                                                 
Total params: 851 (3.32 KB)
Trainable params: 851 (3.32 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [21]:
## MODEL COMPILATION
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [22]:
## TRAINING THE MODEL
hist = model.fit(X_train, y_train, epochs = 100, batch_size = 10,  validation_data = (X_test, y_test))

Epoch 1/100
12/12 [==============================] - 1s 17ms/step - loss: 1.1057 - accuracy: 0.3833 - val_loss: 0.9151 - val_accuracy: 0.6667
Epoch 2/100
12/12 [==============================] - 0s 5ms/step - loss: 0.8262 - accuracy: 0.6667 - val_loss: 0.6978 - val_accuracy: 0.8000
Epoch 3/100
12/12 [==============================] - 0s 5ms/step - loss: 0.6675 - accuracy: 0.7750 - val_loss: 0.5704 - val_accuracy: 0.8333
Epoch 4/100
12/12 [==============================] - 0s 5ms/step - loss: 0.5662 - accuracy: 0.8000 - val_loss: 0.4873 - val_accuracy: 0.8667
Epoch 5/100
12/12 [==============================] - 0s 5ms/step - loss: 0.5000 - accuracy: 0.8000 - val_loss: 0.4247 - val_accuracy: 0.8667
Epoch 6/100
12/12 [==============================] - 0s 7ms/step - loss: 0.4468 - accuracy: 0.8083 - val_loss: 0.3760 - val_accuracy: 0.8667
Epoch 7/100
12/12 [==============================] - 0s 5ms/step - loss: 0.4077 - accuracy: 0.8333 - val_loss: 0.3375 - val_accuracy: 0.9000
Epoch 8/100


In [23]:
## MODEL PREDICTION FROM TEST DATA
predictions = model.predict(X_test)

1/1 [==============================] - 0s 59ms/step


In [24]:
## CONVERTING THE PREDICTION TO THEIR CLASS LABELS

predicted_classes = np.argmax(predictions, axis=1)
predicted_classes

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [25]:
## COMPARING THE PREDICTED LABELS WITH THEIR TRUE LABELS
true_classes = np.argmax(y_test, axis=1)
print("Predictions:", predicted_classes)
print("True Labels:", true_classes)

Predictions: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
True Labels: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [26]:
## MODEL EVALUATION
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Test Accuracy:", accuracy)

1/1 [==============================] - 0s 131ms/step - loss: 0.0128 - accuracy: 1.0000
Loss: 0.012766236439347267
Test Accuracy: 1.0
